# Generated by Django 4.2.6 on 2023-10-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoken', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vid', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
